### ISSUE TITLE
Laraning tutorial videos

### ISSUE THREAD

**Issue by laraning** [JordanDalton/laracrunch-internals#4]
Hi Jordan,

Congratulations for the Laracrunch! Great idea :)

I would request if you could add my website video tutorials (www.laraning.com) about Laravel, since I just to tutorials about our amazing framework.

I publish new videos each week.

Let me know what you need and I'll make sure it happens.

Cheers,
Bruno.

**Comment by JordanDalton** [comment]
Do you have a rss feed?

**Comment by laraning** [comment]
Hi Jordan,

I'm implemented the RSS functionality at the moment, will let you know the URL next week :)

Thanks for accepting my request!

Cheers,
Bruno Falcão

**Comment by laraning** [comment]
Hi Jordan,

Here it is: https://www.laraning.com/feed

Let me know if you need anything else. Thanks!

Cheers,
Bruno

**Comment by JordanDalton** [comment]
It looks like https://www.laraning.com/feed is not returning xml. I looks like you're possibly rendering it inside your @yield('content')

**Comment by laraning** [comment]
Hi Jordan,

The response mime type was incorrect. Now returns text/xml.

Already deployed a new version for you to test.

Also, I've checked with:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.laraning.com%2Ffeed
And it looks okay.

Thank you!
Bruno

**Comment by JordanDalton** [comment]
Your site is now integrated :)
